Code smell
Star-Academy/Summer1400-SE-Team15 pull request #2
Opened 2021-07-26 07:14 UTC by arianpotter

2021-07-26 09:23 UTC, MKasaei00 requested changes
بیش تر به تک منظوره بودن اجزا ی برنامه توجه کنین کلاس‌ها و توابع 
و کلا در کلاس‌هایی که پردازش می‌کنند نباید چیزی چاپ بشه

2021-07-26 09:23 UTC, MKasaei00 commented on Phase02/src/InvertedIndex.java
> +            this.stopWords = Files.readAllLines(Paths.get("utilities/stopWords.txt"));
بهتره این کلاس با فایل‌ها مستقیم کار نکنه

2021-07-26 09:23 UTC, MKasaei00 commented on Phase02/src/InvertedIndex.java
> +        return content.toLowerCase().replaceAll("\\W+", " ");
این خط از کد وظیفه‌ی نرمال‌سازی رشته را داره و از نظر مفهومی یک تابع مستقل هست

2021-07-26 09:23 UTC, MKasaei00 commented on Phase02/src/InvertedIndex.java
> +        return content.toLowerCase().replaceAll("\\W+", " ");
و می‌تونید رشته‌ی regex را به صورت
public static final تعریف کنید

2021-07-26 09:23 UTC, MKasaei00 commented on Phase02/src/InvertedIndex.java
> +            System.out.println("word not found...");
داخل کلاس نباید درگیر ورودی و خروجی به کنسول بشیم و فقط نتایج را بر می‌گردونیم تابع اصلی باید ورودی و خروجی را مدیریت کنه

2021-07-26 09:23 UTC, MKasaei00 commented on Phase02/src/InvertedIndex.java
> +    private void tokenize(List<File> docs){
بهتره ورودی این تابع تعدادی رشته باشه برای اینکه تابع تک منظوره تر بشه و بتونیم رشته‌هایی که از هر جایی اومدن (مستقل از فایل) را با اون تحلیل کنیم.

2021-07-26 09:23 UTC, MKasaei00 commented on Phase02/src/MainClass.java
> +        FileReader fileReader = new FileReader("EnglishData");
اسم پوشه‌ای که قراره داده‌ها خونده بشن به صورت ثابت تعریف بشه یا از args بخونیم

2021-07-26 09:23 UTC, MKasaei00 commented on Phase02/src/MainClass.java
> +        Scanner scanner = new Scanner(System.in);
از نظر منطقی و اصولی بعد از اتمام کار با اسکنر باید close کنیم.

2021-07-26 09:23 UTC, MKasaei00 commented on Phase02/src/SearchEngine.java
> +        String modifiedQuery = query.toLowerCase();
نرمال سازی کلمات مورد جست‌وجو به صورت یک تابع جدا باشه

2021-07-26 09:23 UTC, MKasaei00 commented on Phase02/src/SearchEngine.java
> +            System.out.println("result not found");
نتایج به صورت مستقیم چاپ نشه 
می‌شه استثنا پرتاب کرد یا نتایج را خالی برگردونیم و خارج از کلاس‌های عملکردی چاپ انجام بشه

2021-07-26 09:23 UTC, MKasaei00 commented on Phase02/src/SearchEngine.java
> +        for (String word : query.split(" ")){
جداسازی کلمات یک کوئری از نظر منطقی یک تابع مجزاست

2021-07-26 09:23 UTC, MKasaei00 commented on Phase02/src/FileReader.java
> +    }
نیازی به تبدیل به لیست نیست با همان آرایه که از folder.listfiles() برگردونده می‌شه می‌تونید کار کنید
کار اضافیه

2021-07-26 12:01 UTC, arianpotter commented on Phase02/src/SearchEngine.java
> +        String modifiedQuery = query.toLowerCase();
toLowerCase
خودش یک تابع مفهوم داره و خوانا است ما دوباره هم بخواهیم تابع بنویسیم مشابه همین خواهد شد

2021-07-26 12:01 UTC, arianpotter commented on Phase02/src/SearchEngine.java
> +        for (String word : query.split(" ")){
split
خودش یک تابع مفهوم داره و خوانا است ما دوباره هم بخواهیم تابع بنویسیم مشابه همین خواهد شد

2021-07-26 12:09 UTC, MKasaei00 commented on Phase02/src/SearchEngine.java
> +        String modifiedQuery = query.toLowerCase();
<div dir='rtl'>

درسته که یک تابع جدا داریم براش و کار ساده‌ای هست ولی ممکنه که در آینده نیاز باشه که این آرایه‌ها مثلا در رابط کاربری نرم‌افزار باشند و از تعداد باکس متوالی دریافت بشن

پس بهتره که این تابع فقط وابسته به مجموعه‌ای از کلیدواژه‌ها باشه نه لزوما رشته‌ای که با ترکیب فاصله‌دارشون ساخته شده.

</div>

2021-07-26 12:11 UTC, MKasaei00 commented on Phase02/src/SearchEngine.java
> +        for (String word : query.split(" ")){
<div dir='rtl'>
بهتره اول کوئری پردازش بشه و به صورت آرایه در بیاد که دستمون باز باشه با هر روشی دوست داشتیم کوئری را از کاربر بگیریم.

</div>

2021-07-26 12:23 UTC, MKasaei00 commented on Phase01/src/FileReader.java
> +    public static final String nonCharRegex = "\\W+";
<div dir='rtl'>

نام‌گذاری ثابت‌ها در جاوا به صورت NON_CHAR_REGEX درسته
</div>

2021-07-26 12:23 UTC, MKasaei00 commented on Phase01/src/InvertedIndex.java
> +    public InvertedIndex(FileReader _fileReader){
<div dir='rtl'>

نام پارامتر پارامتر تابع می‌تونه با نام فیلد کلاس یکی باشه و مشکلی نیست
کلا گفتم بدونید

</div>

2021-07-26 12:23 UTC, MKasaei00 commented on Phase01/src/InvertedIndex.java
> +                            .of(doc.getY().split(" "))
<div dir='rtl'>

تو همین استریم میشه فیلتر کرد و تمام عبارت‌های خالی را حذف کرد که تو حلقه‌ی بعدی نیاز نباشه درگیر باشیم و continue کنیم.
</div>

2021-07-26 12:23 UTC, MKasaei00 commented on Phase01/src/MainClass.java
> +        final String stopWordsPath = "utilities/stopWords.txt";
<div dir='rtl'>

نام‌گذاری
</div>

2021-07-26 12:23 UTC, MKasaei00 commented on Phase01/src/Tuple.java
> +    public Y y;
<div dir='rtl'>

اسم متغییر‌ها معنی نمیده
با توجه به استفاده‌ها میشه اسم بهتری انتخاب کرد.
</div>

2021-07-26 12:23 UTC, MKasaei00 commented on Phase02/EnglishData/57110
> +I have a 42 yr old male friend, misdiagnosed as havin osteopporosis for two years, who recently found out that hi illness is the rare Gaucher's disease.Gaucher's disease symptoms include: brittle bon
<div dir='rtl'>

فایل‌های تست متن نباید توی ریپو باشه
</div>

2021-07-27 11:56 UTC, mostmand requested changes

2021-07-27 11:56 UTC, mostmand commented on Phase02/src/FileReader.java
> +    String stopWordsPath;
stopWordsPath
هم می‌تونه
final
تعریف شه

2021-07-27 11:56 UTC, mostmand commented on Phase02/src/FileReader.java
> +            return new ArrayList<>();
ریترن کردن توی
finally
کار اشتباهیه
https://stackoverflow.com/questions/18205493/can-we-use-return-in-finally-block

2021-07-27 11:56 UTC, mostmand commented on Phase02/src/InvertedIndex.java
> +            for (String word : allWords){
فور داخل یه فور دیگه بهتره به عنوان تابع استخراج بشه

2021-07-27 11:56 UTC, mostmand commented on Phase02/src/InvertedIndex.java
> +    private void tokenize(List<Tuple<String,String>> docs,List<String> stopWords){
بهتره این تابع اون هش‌مپ رو بسازه و خروجی بده به جای این که
void
باشه این طوری می‌تونی هش‌مپ رو توی کانستراکتور ست کنی و 
dataHashMap
به صورت
final
تعریف بشه

2021-07-27 11:56 UTC, mostmand commented on Phase02/src/InvertedIndex.java
> +                if (dataHashMap.containsKey(word)){
این قسمت بهتره این طوری نوشته بشه:
```java
if (!dataHashMap.containsKey(word)) {
    dataHashMap.put(word, new HashSet<String>());
}
dataHashMap.get(word).add(doc.getX());
```

2021-07-27 11:56 UTC, mostmand commented on Phase02/src/InvertedIndex.java
> +        if (!dataHashMap.containsKey(word)) {
می‌تونی از تابع
getOrDefault
استفاده کنی:
```java
return dataHashMap.getOrDefault(word, new HashSet<>());
```

2021-07-27 11:56 UTC, mostmand commented on Phase02/src/MainClass.java
> +        FileReader fileReader = new FileReader(folderPath,stopWordsPath);
تابع
main
صرفاً باید کار رو به سایر کلاس‌ها بسپاره و کارچرخانی کنه نباید خودش کاری انجام بده

2021-07-27 11:56 UTC, mostmand commented on Phase02/src/Tuple.java
> +public class Tuple<X, Y> {
به جای این کلاس تاپل جنریک از یک کلاس خاص منظوره با نام‌گذاری‌های مناسب استفاده کنید

2021-07-27 14:42 UTC, MKasaei00 reviewed
چند تا کامنت ساده بود اصلاح کنید 
خسته نباشید

2021-07-27 14:42 UTC, MKasaei00 commented on Phase02/src/MainClass.java
> +        final String STOP_WORDS_PATH = "utilities/stopWords.txt";
<div dir='rtl'>
اینا می‌تونن استاتیک باشن
<dir>

2021-07-27 14:42 UTC, MKasaei00 commented on Phase02/src/MainClass.java
> +        InputScanner scanner = new InputScanner(searchEngine);
<div dir='rtl'>
اینا می‌تونن فاینال باشن
<dir>

2021-07-27 14:42 UTC, MKasaei00 commented on Phase02/src/SearchEngine.java
> +
<div dir='rtl'>
می‌تونن فاینال باشن
<dir>

2021-07-27 15:00 UTC, MKasaei00 approved these changes
خسته نباشید

2021-07-28 03:51 UTC, mostmand approved these changes
احسنت

2021-07-28 05:08 UTC, merged

2021-08-03 05:49 UTC, parsasharify commented
اینجا توی تابع مین رو میتونید یه تابع مال منید که خیلی شلوغ نباشه داخل تابع مین

public static void main(String[] args) {

        final FileReader fileReader = new FileReader(FOLDER_PATH,STOP_WORDS_PATH);
        final InvertedIndex invertedIndex = new InvertedIndex(fileReader);
        final SearchEngine searchEngine = new SearchEngine(invertedIndex);
        final InputScanner scanner = new InputScanner(searchEngine);

        scanner.ScanInput();
    }

2021-08-04 11:12 UTC, mjmaher987 reviewed
به جز چند مورد کلین کد چیز دیگه ای ندیدم. کلین کد ها هم بیشتر چیزهای ریز بودن که اگه
 ctrl + alt + Enter
 بزنیم خود اینتلیج اوکی میکنه