Feature/unit test
Star-Academy/Summer1400-SE-Team15 pull request #3
Opened 2021-07-31 07:21 UTC by arianpotter

2021-08-01 03:06 UTC, MKasaei00 requested changes
<div dir='rtl'>
وقتی یک کلاس از کلاس‌های دیگه به عنوان ورودی استفاده کرده ، باید اینترفیس اون کلاس را ماک کنید
</div>

2021-08-01 03:06 UTC, MKasaei00 commented on Phase03/EnglishDataTest/57110
> +I have a 42 yr old male friend, misdiagnosed as havin osteopporosis for two years, who recently found out that hi illness is the rare Gaucher's disease.Gaucher's disease symptoms include: brittle bon
<div dir='rtl'>
برای تست فایل‌ها می‌تونید از فایل‌ها با متن‌های ساده و کوتاه استفاده که تمرکز روی سناریو تست باشه
</div>

2021-08-01 03:06 UTC, MKasaei00 commented on Phase03/src/main/java/InputScanner.java
> +            }
<div dir='rtl'>
منطق این تابع را از خواندن ورودی و خروجی جدا کنید قسمت‌های بیش‌تری قابل تست خواهند بود.
</div>

2021-08-01 03:06 UTC, MKasaei00 commented on Phase03/src/test/java/SearchEngineTest.java
> +        assertTrue(results.contains("57110"),"search engine is wrong");
<div dir='rtl'>
بهتره کل محتوای فایل از جلمه کاراکتر اول و آخر را حتما بررسی کنید
تو خوندن فایل همه‌ی کاراکتر‌ها مهمه
</div>

2021-08-01 03:06 UTC, MKasaei00 commented on Phase03/src/test/java/InvertedIndexTest.java
> +        HashSet<String> result = invertedIndex.getResultListByWord("poet");
<div dir='rtl'>
در یونیت تستینگ باید فقط و فقط یک بخش کوچک از کد تست بشه

ما باید تمام کلاس های وابسته به یک کلاس را ماک کنیم و در اختیار کلاس اصلی که تحت تست هست قرار بدیم و نباید عملکرد اصلی خود کلاس استفاده بشه
</div>

2021-08-01 03:06 UTC, MKasaei00 commented on Phase03/src/test/java/FileReaderTest.java
> +        assertEquals("i have a 42 yr old male friend misdiagnosed as havin osteopporosis for two years who recently found out that hi illness is the rare gaucher s disease gaucher s disease symptoms
<div dir='rtl'>
متن داخل فایل حتما کوتاه‌تر بشه که تمرکز روی منطق کد باشه
</div>

2021-08-01 03:06 UTC, MKasaei00 commented on Phase03/.gitignore
> +EnglishData/
<div dir='rtl'>
فایل‌های باینری .class رو هم باید ایگنور کیند
</div>

2021-08-01 03:06 UTC, MKasaei00 commented on Phase03/src/main/java/MainClass.java
> +        final InputScanner scanner = new InputScanner(searchEngine);
<div dir='rtl'>
فکر می‌کنم اینا رو بشه به صورت فیلد کلاس تعریف کرد که خط‌های تابع اصلی کم‌تر باشه
</div>

2021-08-01 03:06 UTC, MKasaei00 commented on Phase03/src/test/java/SearchEngineTest.java
> +        SearchEngine searchEngine = new SearchEngine(invertedIndex);
<div dir='rtl'>
کلاس‌ها رو ماک کنید
</div>

2021-08-01 05:01 UTC, arianpotter commented on Phase03/src/main/java/MainClass.java
> +        final InputScanner scanner = new InputScanner(searchEngine);
تست کردیم هیچ تفاوتی ایجاد نمیکنه

2021-08-01 06:57 UTC, NaserFarajzade commented on Phase03/src/test/java/SearchEngineTest.java
> +        assertTrue(results.contains("57110"),"search engine is wrong");
منطق تست به اینصورت هست که میخواهیم مقادیر داخل یک آرایه به نام
result
رو چک کنیم که آیا شامل "59652" و "57110" هست یا نه 
اول سایز آرایه که 2 باید باشه رو چک میکنیم و بعد هریک از اعضای آرایه رو

2021-08-04 11:04 UTC, mjmaher987 requested changes
من چند تا کامنت گذاشتم

2021-08-04 11:04 UTC, mjmaher987 commented on Phase03/src/test/java/FileReaderTest.java
> +        }
میتونه تابع جداگانه باشه

2021-08-04 11:04 UTC, mjmaher987 commented on Phase03/src/test/java/InvertedIndexTest.java
> +        stopWords.add("of");
به جای این خطوط این کدرو میشه زد:
stopWords = Arrays.asList("i", "have", "a", ...);

2021-08-04 11:04 UTC, mjmaher987 commented on Phase03/src/test/java/SearchEngineTest.java
> +    //static final FileReader fileReader = mock(FileReader.class);
اگر در این فاز هم اصول کلین کد مطرح باشه، این خط کامنت باید برداشته بشه

2021-08-07 04:48 UTC, MKasaei00 approved these changes

2021-08-07 06:33 UTC, NaserFarajzade commented on Phase03/src/test/java/FileReaderTest.java
> +        }
بنظرم جدا کردن این این قطعه از کد و تابع کردنش بیشتر باعث سردرگمی خواننده کد بشه چون این قسمت وظیفه خاصی رو انجام نمیده که بخوایم تبدیل به تابعش کنیم.

بقیه نظراتتون اعمال شد.ممنون

2021-08-07 07:06 UTC, mostmand requested changes
یه تعدادی کامنت گذاشته شد ولی در کل خوب بود

2021-08-07 07:06 UTC, mostmand commented on Phase03/src/main/java/InvertedIndex.java
> +        return Arrays.stream(doc.split(" ")).filter(e -> e.trim().length() > 0).toArray(String[]::new);
هر
operation
را در یک خط بگذارید تا خواناتر شود:
```java
return Arrays.stream(doc.split(" "))
    .filter(e -> e.trim().length() > 0)
    .toArray(String[]::new);
```

2021-08-07 07:06 UTC, mostmand commented on Phase03/src/main/java/MainClass.java
> +        final FileReader fileReader = new FileReader(FOLDER_PATH,STOP_WORDS_PATH);
به جای استفاده‌ی مستقیم از کلاس‌ها برای هر کدام اینترفیسی تعریف کنید و از آن اینترفیس‌ها استفاده کنید

2021-08-07 07:06 UTC, mostmand commented on Phase03/src/test/java/InputScannerTest.java
> +    public void ShouldExit(){
این کلاس چرا هیچ کاری نمی‌کنه؟ اگر هیچ‌کاره است حذف بشه

2021-08-07 07:06 UTC, mostmand commented on Phase03/src/test/java/SearchEngineTest.java
> +        HashSet<String> listOfWord_old = new HashSet<>();
قواعد نام‌گذاری رعایت بشه توی نام متغیرها آندرلاین گذاشته نمیشه

2021-08-07 12:37 UTC, mjmaher987 approved these changes

2021-08-08 07:10 UTC, MKasaei00 approved these changes

2021-08-10 06:08 UTC, mostmand approved these changes
نام‌گذاری‌ها رو اصلاح کنید و بعد مرج کنید

2021-08-10 06:08 UTC, mostmand commented on Phase03/src/main/java/IFileReader.java
> +public interface IFileReader {
نام‌گذاری اینترفیس‌ها در جاوا با سی‌شارپ فرق می‌کنه توی سی‌شارپ اولش
I
می‌ذارن ولی توی جاوا این طور نیست البته فعلاً بیخیال چون ما دیگه با جاوا کاری نداریم فعلاً

2021-08-10 06:08 UTC, mostmand commented on Phase03/src/main/java/InputScanner.java
> +    final private ISearchEngine ISearchEngine;
اسم فیلد با حرف کوچیک شروع میشه اینجا همون
searchEngine
اسم مناسبیه

2021-08-10 06:08 UTC, mostmand commented on Phase03/src/main/java/InvertedIndex.java
> +    public InvertedIndex(IFileReader IFileReader){
اسم ورودی تابع با حرف کوچیک شروع میشه اینجا همون
fileReader
مناسب‌تره

2021-08-10 06:08 UTC, mostmand commented on Phase03/src/main/java/MainClass.java
> +        final IFileReader IFileReader = new FileReader(FOLDER_PATH,STOP_WORDS_PATH);
اسم متغیر با حرف کوچیک شروع میشه اینجا همون نام‌های قبلی مناسب‌تره

2021-08-10 06:08 UTC, mostmand commented on Phase03/src/main/java/MainClass.java
> +        final IFileReader IFileReader = new FileReader(FOLDER_PATH,STOP_WORDS_PATH);
تو فایل‌های دیگه هم این ایراد وجود داره که من دیگه کامنت نمی‌ذاریم ولی خودتون اصلاحشون کنید

2021-08-10 06:30 UTC, merged