Phase04
Star-Academy/Summer1400-SE-Team15 pull request #4
Opened 2021-08-03 08:36 UTC by NaserFarajzade

2021-08-04 11:07 UTC, mjmaher987 approved these changes
من ایراد خاصی پیدا نکردم

2021-08-07 04:47 UTC, MKasaei00 requested changes

2021-08-07 04:47 UTC, MKasaei00 commented on Phase04/Phase04/readingJson/AverageCalculator.cs
> +            List<StudentAverage> list = new List<StudentAverage>();
از 
var 
استفاده کنید.

2021-08-07 04:47 UTC, MKasaei00 commented on Phase04/Phase04/readingJson/AverageCalculator.cs
> +            }
میتونید
query 
را مستقیم به لیست تبدیل کنید و نیازی به تولید دستی لیست نیست

2021-08-07 04:47 UTC, MKasaei00 commented on Phase04/Phase04/readingJson/AverageCalculator.cs
> +        }
بهتره که عدد ۳ به عنوان پارامتر برای تابع باشه و منعطف‌تر بشه

2021-08-07 04:47 UTC, MKasaei00 commented on Phase04/Phase04/readingJson/Program.cs
> +            List<Score> scores = scoreSerializer.Deserialize(scoreReader.GetFileContent());
اون جاهایی که مقداردهی همزمان با تعریف متغییر انجام میشه از 
var 
استفاده کنید.

2021-08-07 04:47 UTC, MKasaei00 commented on Phase04/Phase04/readingJson/Program.cs
> +            List<Score> scores = scoreSerializer.Deserialize(scoreReader.GetFileContent());
و بعضا جاهای دیگه

2021-08-07 04:47 UTC, MKasaei00 commented on Phase04/Phase04/readingJson/Program.cs
> +
چاپ مقادیر وظیفه‌ی یک تابع یا حتی یک کلاس مستقل هست

2021-08-07 04:47 UTC, MKasaei00 commented on Phase04/Phase04/readingJson/resources/Scores.json
> +[
حضور این فایل‌ها توی ریپو لازم نیست 
ولی چون حجم فایل‌ها کم هس و ساختار داده را نشان میده به نظر من اشکالی نداره

2021-08-07 11:55 UTC, mostmand requested changes
نسبتاً خوب بود ولی یه تعدادی کامنت هم گذاشته شد

2021-08-07 11:55 UTC, mostmand commented on Phase04/Phase04/readingJson/AverageCalculator.cs
> +            var query = from score in _scores
Method Syntax
نسبت به
Query Syntax
خواناتره

2021-08-07 11:55 UTC, mostmand commented on Phase04/Phase04/readingJson/FileReader.cs
> +        private string _path ;
آدرس فایل می‌تونه به عنوان ورودی تابع
GetFileContent
گرفته بشه

2021-08-07 11:55 UTC, mostmand commented on Phase04/Phase04/readingJson/Program.cs
> +            averageCalculator.GetTopThreeStudents().ForEach((n) => Console.WriteLine(n.StudentNumber + " " + n.FirstName + " " + n.LastName + " " + n.Average));
برای ورودی لامبداها نام مناسب بگذارید مثلاً این‌جا به جای
n
می‌توانید
student
بگذارید

2021-08-07 11:55 UTC, mostmand commented on Phase04/Phase04/readingJson/StudentSerializer.cs
> +    class StudentSerializer
access modifier
کلاس به طور صریح بیان بشه مثلاً این‌جا:
internal class StudentSerializer

2021-08-07 11:55 UTC, mostmand commented on Phase04/Phase04/readingJson/StudentSerializer.cs
> +    class StudentSerializer
یک اینترفیس داشته باشید و این کلاس اون اینترفیس رو پیاده‌سازی کنه

2021-08-08 10:13 UTC, MKasaei00 approved these changes
<div dir='rtl'>
خسته نباشید :)
</div>

2021-08-10 06:00 UTC, mostmand approved these changes

2021-08-10 06:30 UTC, merged