Phase05
Star-Academy/Summer1400-SE-Team15 pull request #5
Opened 2021-08-08 10:16 UTC by arianpotter

2021-08-08 10:35 UTC, mjmaher987 requested changes

2021-08-08 10:35 UTC, mjmaher987 commented on Phase05/SearchEngineLibrary/SearchEngineLibrary.Test/InvertedIndexTest.cs
> +        }
قاعده ی کلین کد زیر 30 خط نمیدونم در تست نویسی هم مهمه یا نه ولی اگه باشه اینجا رعایت نشده

2021-08-08 10:35 UTC, mjmaher987 commented on Phase05/SearchEngineLibrary/SearchEngineLibrary/EngineStarter.cs
> +                if (query.Equals(ExitQuery)) break;
فکر میکنم بدنه ی ایف باید در خط مجزا باشه

2021-08-09 04:33 UTC, MKasaei00 requested changes

2021-08-09 04:33 UTC, MKasaei00 commented on Phase05/SearchEngineLibrary/SearchEngineLibrary.Test/FileReaderTest.cs
> +            Tuple<string, string> temp = null;
تا جایی که امکان داره از 
var 
استفاده کنین

2021-08-09 04:33 UTC, MKasaei00 commented on Phase05/SearchEngineLibrary/SearchEngineLibrary.Test/FileReaderTest.cs
> +            }
به جای این حلقه می‌تونید از دستور 
where
استفاده کنین

2021-08-09 04:33 UTC, MKasaei00 commented on Phase05/SearchEngineLibrary/SearchEngineLibrary.Test/FileReaderTest.cs
> +            Tuple<string, string> temp = null;
در بقیه‌ی قسمت‌ها هم لطفا اصلاح کنین

2021-08-09 04:33 UTC, MKasaei00 commented on Phase05/SearchEngineLibrary/SearchEngineLibrary.Test/InvertedIndexTest.cs
> +
خط‌های خالی اضافه را حذف کنین

2021-08-09 04:33 UTC, MKasaei00 commented on Phase05/SearchEngineLibrary/SearchEngineLibrary/FileReader.cs
> +            return filesContent;
با دستور 
select
این کار ساده‌تر انجام میشه

2021-08-09 04:33 UTC, MKasaei00 commented on Phase05/SearchEngineLibrary/SearchEngineLibrary/IFileReader.cs
> +        public List<string> GetStopWords();
کلیدواژه
public
برای اینترفیس ها لازم نیست و به صورت پیش‌فرض عمومی هستند

2021-08-09 04:33 UTC, MKasaei00 commented on Phase05/SearchEngineLibrary/SearchEngineLibrary/InputScanner.cs
> +            if (!output.Any())
به جای نقیض
any
می‌تونید از 
exists
استفاده کنید

2021-08-09 04:33 UTC, MKasaei00 commented on Phase05/SearchEngineLibrary/SearchEngineLibrary/InvertedIndex.cs
> +            Dictionary<string, HashSet<string>> output = new Dictionary<string, HashSet<string>>();
var
را در تمام قسمت های کدتون اعمال کنین

2021-08-09 04:33 UTC, MKasaei00 commented on Phase05/SearchEngineLibrary/SearchEngineLibrary/SearchEngine.cs
> +                if (!result.Any()){
Exists

2021-08-10 05:33 UTC, mostmand approved these changes
خوب بود اپروو کردم ولی یکی دو تا کامنت هم گذاشتم اونا رو درست کنید بعد مرج کنید

2021-08-10 05:33 UTC, mostmand commented on Phase05/SearchEngineLibrary/SearchEngineLibrary/FileReader.cs
> +            content = NonCharRegex.Replace(content, " ");
ورودی تابع رو عوض نکن و متغیر جدید تعریف کن

2021-08-10 05:33 UTC, mostmand commented on Phase05/SearchEngineLibrary/SearchEngineLibrary/IFileReader.cs
> +        public List<string> GetStopWords();
پس پابلیک رو از اول تعاریف تابع‌ها توی اینترفیس بردارید دیگه

2021-08-10 05:33 UTC, mostmand commented on Phase05/SearchEngineLibrary/SearchEngineLibrary/InvertedIndex.cs
> +                outputDictionary.TryAdd(word, new HashSet<string>());
بهتره این طوری نوشته بشه:
```csharp
if (!outputDictionary.TryGetValue(word, out var postingList))
{
    postingList = new HashSet<string>();
    outputDictionary.Add(word, postingList);
}
postingList.Add(docName);
```
این طوری صرفاً یک بار در دیکشنری می‌گردیم

2021-08-10 06:23 UTC, MKasaei00 approved these changes

2021-08-10 06:42 UTC, merged