Phase08
Star-Academy/Summer1400-SE-Team15 pull request #6
Opened 2021-08-12 10:49 UTC by arianpotter

2021-08-12 14:42 UTC, MKasaei00 requested changes
<div dir='rtl'>
خسته نباشین خوب بود

فقط چند تا کامنت ساده گذاشتم 
</div>

2021-08-12 14:42 UTC, MKasaei00 commented on Phase08/SearchEngineEfCore/SearchEngineEfCore/DatabaseClass.cs
> +    public class DatabaseClass : IDatabase
<div dir='rtl'>
نیازی به پیشوند 
class 
نیست و میشه نام پیاده‌سازی به صورت
Database
هم گذاشت

هر طور راحتین
</div>

2021-08-12 14:42 UTC, MKasaei00 commented on Phase08/SearchEngineEfCore/SearchEngineEfCore/DatabaseClass.cs
> +                var wrd = new WordModel()
<div dir='rtl'>
مخفف‌های غیر معروف را به عنوان نام متغییر استفاده نشه بهتره
</div>

2021-08-12 14:42 UTC, MKasaei00 commented on Phase08/SearchEngineEfCore/SearchEngineEfCore/DatabaseClass.cs
> +                var wrd = context.Words
<div dir='rtl'>
مخفف‌های غیر معروف به عنوان نام متغییر استفاده نشه بهتره

</div>

2021-08-12 14:42 UTC, MKasaei00 commented on Phase08/SearchEngineEfCore/SearchEngineEfCore/config.json
> +  "standard" : "Server=.;Database=SearchEngineDB;User Id=sa;Password=YourPassword",
<div dir='rtl'>
به نظرم کانفیگ‌ها می‌تونه ریزدانه تر باشه و مثلا متغییرهایی مثل آدرس سرور و نام پایگاه و اینا را داشته باشین
</div>

2021-08-12 14:42 UTC, MKasaei00 commented on Phase08/SearchEngineEfCore/SearchEngineEfCore/config.json
> +  "standard" : "Server=.;Database=SearchEngineDB;User Id=sa;Password=YourPassword",
<div dir='rtl'>
یعنی همه چیز را بشه از فایل کانفیک انتخاب کرد و نیازی به تغییر کد اصلا نیاز نباشه
</div>

2021-08-12 14:42 UTC, MKasaei00 commented on Phase08/SearchEngineEfCore/SearchEngineEfCore/IFileReader.cs
> +        List<Tuple<string, string>> GetFilesContents();
<div dir='rtl'>
اگر به جای تاپل از یک کلاس خاص استفاده کنین به نظر کد خوانا تر میشه
</div>

2021-08-12 14:42 UTC, MKasaei00 commented on Phase08/SearchEngineEfCore/SearchEngineEfCore/IFileReader.cs
> +        List<Tuple<string, string>> GetFilesContents();
<div dir='rtl'>
کلاسی که مفهوم و حالتی که استفاده می‌کنید را بهتر نشون بده
</div>

2021-08-13 16:12 UTC, MKasaei00 approved these changes
<div dir='rtl'>
خسته نباشین :)
</div>

2021-08-15 12:01 UTC, mostmand approved these changes

2021-08-15 14:32 UTC, merged