webapi for searchengine created and tested with index post and get me…
Star-Academy/Summer1400-SE-Team15 pull request #7
Opened 2021-08-15 14:58 UTC by arianpotter

…thods

2021-08-16 04:31 UTC, mostmand requested changes

2021-08-16 04:31 UTC, mostmand commented on Phase11/SearchEngineApi/Controllers/Query.cs
> +        public IActionResult Post(Doc doc,[FromServices] IInvertedIndex invertedIndex)
چرا
IInvertedIndex
رو توی کانستراکتور نگرفتی؟

2021-08-16 04:31 UTC, mostmand commented on Phase11/SearchEngineApi/Controllers/Query.cs
> +        public IActionResult Get([FromServices] ISearchEngine searchEngine)
چرا
ISearchEngine
رو توی کانستراکتور نگرفتی؟

2021-08-16 04:31 UTC, mostmand commented on Phase11/SearchEngineApi/Controllers/Query.cs
> +            if (!HttpContext.Request.Query.TryGetValue("q", out var query)) return BadRequest();
کوئری رو می‌تونی توی ورودی تابع بگیری و از
FromQuery Attribute
استفاده کنی:
```csharp
public IActionResult Get([FromQuery(Name = "q")] string query)
```

2021-08-16 04:31 UTC, mostmand commented on Phase11/SearchEngineApi/DatabaseFunctions.cs
> +            using (var context = new SearchEngineContext(_configuration))
کانتکست رو توی ورودی کانستراکتور بگیر و توی یک فیلد
private readonly
ذخیره‌اش کن و هر بار
using
نزن به جاش این کلاس و اینترفیسش رو
IDisposable
کن و توی متد دیسپوز کانتکست رو دیسپوز کن

2021-08-16 04:31 UTC, mostmand commented on Phase11/SearchEngineApi/DatabaseFunctions.cs
> +            using (var context = new SearchEngineContext(_configuration))
البته باید کانتکست رو هم در ابتدای برنامه توی سرویس‌هات
inject
کنی

2021-08-16 05:44 UTC, arianpotter commented on Phase11/SearchEngineApi/Controllers/Query.cs
> +        public IActionResult Post(Doc doc,[FromServices] IInvertedIndex invertedIndex)
چون که فقط توی همین یدونه تابع استفاده داشت به نظر میشد اینجوری هم گرفتش

2021-08-16 05:45 UTC, arianpotter commented on Phase11/SearchEngineApi/Controllers/Query.cs
> +        public IActionResult Get([FromServices] ISearchEngine searchEngine)
چون که توی همین یدونه تابع استفاده داشت نه بیشتر

2021-08-16 12:59 UTC, MKasaei00 approved these changes
خسته نباشین :)

2021-08-22 07:23 UTC, mostmand approved these changes
خسته نباشید عالی

2021-08-22 07:23 UTC, mostmand commented on Phase11/SearchEngineApi/Controllers/Query.cs
> +            if (query == null) return BadRequest();
می‌تونی این شرط رو چک کنی:
if (string.IsNullOrWhitespace(query)) return BadRequest();

2021-08-22 18:13 UTC, merged